### ISSUE TITLE
Code Review

### ISSUE THREAD

**Issue by a-n-g-i-e-r-i** [sbweins/budget-api#1]
Please review the comments associated with this issue and refactor your code accordingly. Thanks!

**Comment by a-n-g-i-e-r-i** [comment]
Consider writing validations for the request body sent by clients to your routes. Its always a good idea when writing an API to include object validations to ensure that what is stored in the backend complies with the expectations your software has for the data.

**Comment by a-n-g-i-e-r-i** [comment]
Make sure to include a link to your deployed API in your README.md

**Comment by sbweins** [comment]
Thanks! Updated ReadME.md with deployed API Link!
